### ISSUE TITLE
Uncaught Error: Cannot find module 'ie-number-polyfill'

### ISSUE THREAD

**Issue by jeroenhoebe** [ekeric13/react-ratings-declarative#1]
I just tried the rating component and it gives the following error:
`Uncaught Error: Cannot find module 'ie-number-polyfill'`

The problem is in the following file `build/index.js` 
line 17 `require('ie-number-polyfill');`
To fix the problem change it to `require('./ie-number-polyfill');` because else it thinks it's a module.

**Comment by ekeric13** [comment]
@jeroenhoebe Modify version 3.2.0 to correctly point the right fule name

https://github.com/ekeric13/react-ratings-declarative/blob/master/build/index.js#L17

**Comment by ekeric13** [comment]
Still giving me issues actually.

**Comment by jeroenhoebe** [comment]
`require('ie-isInteger-polyfill');` you forgot the `./` needs to be `require('./ie-isInteger-polyfill');`

**Comment by ekeric13** [comment]
Yep. Changed it to that and tested it out. Working well for me. v3.3.0
