### ISSUE TITLE
starSpacings and starSpacing doesn't work

### ISSUE THREAD

**Issue by jeroenhoebe** [ekeric13/react-ratings-declarative#2]
On the Ratings component `starSpacings` and on the Widget `starSpacing` doesn't work but when I looked in the React Dev Tools I found the following `widgetSpacings` and `widgetSpacing` when I changed those values it does work. Even when I put them on the component it works. Like this:

```
<Ratings
  ...
  widgetSpacings="1px"
>

<Ratings.Widget widgetSpacing="1px" />
```

Long story short changing the API docs from `starSpacings` and `starSpacing` to `widgetSpacings` and `widgetSpacing`

**Comment by ekeric13** [comment]
Yeah the source of truth is [right here](https://github.com/ekeric13/react-ratings-declarative/blob/master/src/ratings.js#L199) for the props. I must have just done a bad job copying them over to the README.

Thanks for the catch.
